apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  DB_NAME: mydatabase
  DB_USER: myuser
  DB_HOST: postgresql-service
  DB_PORT: 5432
---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  DB_PASSWORD: LDeYE7kgVR